// pragma solidity ^0.4.24;
pragma solidity ^0.5.4;

import "./PorthosContract.sol";

contract Gateway {

  // The Events generated by the framework (outward)

  // Simple Log Messages
  event Log(string message, uint blockNumber, address sender);

  // A request to register a callback at a certain time
  event CallbackRequest(address contractAddress, string methodName, uint timeRequested);

  // A request to cancel a previously registered contract
  event CallbackCancel(address contractAddress, string methodName, uint timeRequested);

  // A crosschain call - calls another address on a specific method
  event CrossChain(string blockchainSystem, address contractAddress, string methodName);

  // A crosschain call to open a gate
  event CCOpenGate(string blockchainSystem, address contractAddress, string assetType, string gateName);

  // A crosschain call to release commitments of type
  event CCReleaseCommitments(string blockchainSystem, address contractAddress, string assetType);

  // A crosschain call to cancel commitments
  event CCCancelCommitments(string blockchainSystem, address contractAddress, string assetType);

  // An event to indicate that a gate has been opened, and the user can now perform his action
  event GateOpened(string gateName);

  // An event to indicate that a gate is closed, by user action or by timeout
  event GateClosed(string gateName, bool timeout);


  // Emitting of Events Section
  function fireMessage(string memory _message) public {
  	emit Log(_message, block.number, tx.origin);
  }

  function requestCallback(address _contractAddress, string memory _methodName, uint _timeRequested) public {
  	emit CallbackRequest(_contractAddress, _methodName, _timeRequested);
  	emit Log("Request Callback", block.number, tx.origin);
  }

  function cancelCallback(address _contractAddress, string memory _methodName, uint _timeRequested) public {
  	emit CallbackCancel(_contractAddress, _methodName, _timeRequested);
  }

  function initiateCCC(string memory _bcSystem, address _contractAddress, string memory _methodName) public {
  	emit CrossChain(_bcSystem, _contractAddress, _methodName);
  }

  function ccOpenGate(string memory _bcSystem, address _contractAddress, string memory _assetType, string memory _gateName) public {
    emit CCOpenGate(_bcSystem, _contractAddress, _assetType, _gateName);
  }

  function ccReleaseCommitments(string memory _bcSystem, address _contractAddress, string memory _assetType) public {
    emit CCReleaseCommitments(_bcSystem, _contractAddress, _assetType);
  }

  function ccCancelCommitments(string memory _bcSystem, address _contractAddress, string memory _assetType) public {
    emit CCCancelCommitments(_bcSystem, _contractAddress, _assetType);
  }

  function gateOpened(string memory _gateName) public {
    emit GateOpened(_gateName);
  }

  function gateClosed(string memory _gateName, bool _timeout) public {
    emit GateClosed(_gateName, _timeout);
  }

  // Call Functions
  // function call(address contractAddress, string memory method) public {
  //   if (!contractAddress.call(abi.encodeWithSignature(bytes4(keccak256(abi.encodePacked(method))))) 
  //   // if (!contractAddress.call(bytes4(keccak256(abi.encodePacked(method))))) 
  //     revert();
  // }

  function openGateCall(address contractAddress, string memory assetType, string memory gateName) public {
    PorthosContract c = PorthosContract(contractAddress);
    c.openGate(assetType, gateName);
  }

  function releaseAllCommitmentsCall(address contractAddress, string memory assetType) public {
    PorthosContract c = PorthosContract(contractAddress);
    c.releaseAllCommitments(assetType);
  }

  function cancelAllCommitmentsCall(address contractAddress, string memory assetType) public {
    PorthosContract c = PorthosContract(contractAddress);
    c.cancelAllCommitments(assetType);
  }
}